// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN7OY92rrc_tgW7Z9bfpS4zzKpVRDsTY0',
    appId: '1:693832998814:web:32f035c517fca19b5e808f',
    messagingSenderId: '693832998814',
    projectId: 'everest-shop-466ae',
    authDomain: 'everest-shop-466ae.firebaseapp.com',
    storageBucket: 'everest-shop-466ae.appspot.com',
    measurementId: 'G-204SN3NBH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf1Ik0qlRVHMAomSU9ghnztgQLAQAto7o',
    appId: '1:693832998814:android:72d3f1cc75037aa75e808f',
    messagingSenderId: '693832998814',
    projectId: 'everest-shop-466ae',
    storageBucket: 'everest-shop-466ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIrDzYxVO2mT4NpxNTOrGGmETUGUGnu7w',
    appId: '1:693832998814:ios:5eb89e4fa6dcb0555e808f',
    messagingSenderId: '693832998814',
    projectId: 'everest-shop-466ae',
    storageBucket: 'everest-shop-466ae.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIrDzYxVO2mT4NpxNTOrGGmETUGUGnu7w',
    appId: '1:693832998814:ios:5eb89e4fa6dcb0555e808f',
    messagingSenderId: '693832998814',
    projectId: 'everest-shop-466ae',
    storageBucket: 'everest-shop-466ae.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN7OY92rrc_tgW7Z9bfpS4zzKpVRDsTY0',
    appId: '1:693832998814:web:0261ed402327e4f85e808f',
    messagingSenderId: '693832998814',
    projectId: 'everest-shop-466ae',
    authDomain: 'everest-shop-466ae.firebaseapp.com',
    storageBucket: 'everest-shop-466ae.appspot.com',
    measurementId: 'G-87RZPREJ99',
  );
}
